# Generated by Django 6.0.2 on 2026-06-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherrfidcard',
            name='teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='uid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='uid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.DeleteModel(
            name='RFIDCard',
        ),
        migrations.DeleteModel(
            name='TeacherRFIDCard',
        ),
    ]
