# Generated by Django 6.0.2 on 2026-06-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_teacherrfidcard_teacher_student_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_num',
            field=models.CharField(default=''),
        ),
    ]
