# Generated by Django 6.0.2 on 2026-06-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student_parent_name_student_parent_num'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classschedule',
            unique_together=set(),
        ),
    ]
